### ISSUE TITLE
Upload fails

### ISSUE THREAD

**Issue by 1zun4** [nerdoza/action-simple-file-upload#22]
Hi there,

 I am trying to upload a file using your action, but somehow it is not going as expected.

![image](https://github.com/bayssmekanique/action-simple-file-upload/assets/12410754/a48c816b-6fd0-47e1-80ca-c3fc39581e0f)

The file is uploaded "successfully", at least there is no error in the log, but when I check the FTP there is no file. Only the folder (which I am in) was created, but there are no files. Meanwhile on my Linux workflow it looks even worse with errors.
![image](https://github.com/bayssmekanique/action-simple-file-upload/assets/12410754/1133c5cb-afde-45b6-9c28-b75e38b1890a)

Manually uploading via WinSCP from my computer works, so it has nothing to do with the FTP server.

```yml
name: Build java-cef 5359

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  java-cef-linux:
    runs-on: [ubuntu-20.04]
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Install deps and build
        run: |
          sudo apt update
          sudo apt install build-essential g++ cmake ninja-build openjdk-17-jdk python3 libgtk2.0-dev -y
          mkdir jcef_build && cd jcef_build
          export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
          export JAVA_INCLUDE_PATH=/usr/lib/jvm/java-17-openjdk-amd64/include
          cmake -G "Ninja" -DPROJECT_ARCH=${{ matrix.platform }} -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          mv native/Release linux_${{ matrix.platform }}
          strip linux_${{ matrix.platform }}/libcef.so
          tar -czf linux_${{ matrix.platform }}.tar.gz linux_${{ matrix.platform }}
          sha256sum linux_${{ matrix.platform }}.tar.gz > linux_${{ matrix.platform }}.tar.gz.sha256
      - name: Upload JCEF
        uses: bayssmekanique/action-simple-file-upload@v2
        with:
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: ${{ secrets.FTP_HOST }}
          src: 'jcef_build/*.{tar.gz,tar.gz.sha256}'
          dest: 'java-cef-builds/${{ github.sha }}/'
          verbose: true
  
  java-cef-windows:
    runs-on: [windows-2022]
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - uses: actions/checkout@v3
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build
        run: |
          mkdir jcef_build && cd jcef_build
          cmake -G "Ninja" -DPROJECT_ARCH=${{ matrix.platform }} -DCMAKE_BUILD_TYPE=Release ..
          ninja -j4
          cd native
          ren Release windows_${{ matrix.platform }}
          cd ..
          move native/windows_${{ matrix.platform }} windows_${{ matrix.platform }}
          tar -czf windows_${{ matrix.platform }}.tar.gz windows_${{ matrix.platform }}
          Get-FileHash -Algorithm SHA256 -Path "windows_${{ matrix.platform }}.tar.gz" | Out-File "windows_${{ matrix.platform }}.tar.gz.sha256"
      - name: Upload JCEF
        uses: bayssmekanique/action-simple-file-upload@v2
        with:
          user: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          host: ${{ secrets.FTP_HOST }}
          src: 'jcef_build/*.{tar.gz,tar.gz.sha256}'
          dest: 'java-cef-builds/${{ github.sha }}/'
          verbose: true
```
